name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  PYTHON_VERSION_DEFAULT: "3.12"

jobs:
  lint-and-format:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          
      - name: Run Ruff linter
        run: |
          ruff check src/ tests/
          
      - name: Run Ruff formatter
        run: |
          ruff format --check src/ tests/
          
      - name: Run Black formatter check
        run: |
          black --check --diff src/ tests/
          
      - name: Run MyPy type checking
        run: |
          mypy src/linear_cli
          
      - name: Check imports with isort
        run: |
          isort --check-only --diff src/ tests/

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13"]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          
      - name: Run unit tests
        run: |
          pytest tests/unit/ -v --tb=short --cov=src/linear_cli --cov-report=xml --cov-report=term-missing
          
      - name: Run integration tests
        run: |
          pytest tests/integration/ -v --tb=short
          
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.PYTHON_VERSION_DEFAULT
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          
      - name: Run Bandit security scan
        run: |
          bandit -r src/linear_cli/ -f json -o bandit-report.json || true
          bandit -r src/linear_cli/
          
      - name: Run Safety vulnerability scan
        run: |
          safety check --json --output safety-report.json || true
          safety check
          
      - name: Upload security artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json

  docs:
    name: Documentation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-docs-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-docs-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
          
      - name: Build documentation
        run: |
          cd docs
          sphinx-build -W -b html . _build/html
          
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: docs/_build/html

  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    needs: [lint-and-format, test, security]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          
      - name: Build source and wheel distributions
        run: |
          python -m build
          
      - name: Check distribution
        run: |
          twine check dist/*
          
      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    needs: [build, docs]
    if: github.event_name == 'release' && github.event.action == 'published'
    environment:
      name: pypi
      url: https://pypi.org/p/linear-cli
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
          
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true

  test-install:
    name: Test Installation
    runs-on: ${{ matrix.os }}
    needs: [build]
    if: github.event_name != 'release'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
          
      - name: Download distribution artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
          
      - name: Test wheel installation
        run: |
          pip install dist/*.whl
          linear --version
          linear --help
          
      - name: Test source installation
        run: |
          pip uninstall -y linear-cli
          pip install dist/*.tar.gz
          linear --version
          linear --help

  performance:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          
      - name: Run performance tests
        run: |
          pytest tests/performance/ -v --benchmark-json=benchmark.json
          
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmark.json

  notify:
    name: Notifications
    runs-on: ubuntu-latest
    needs: [lint-and-format, test, security, docs, build]
    if: always()
    steps:
      - name: Notify on success
        if: ${{ needs.lint-and-format.result == 'success' && needs.test.result == 'success' && needs.security.result == 'success' && needs.docs.result == 'success' && needs.build.result == 'success' }}
        run: |
          echo "✅ All CI checks passed successfully!"
          
      - name: Notify on failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          echo "❌ CI pipeline failed. Check the logs for details."
          exit 1